replicaCount: 4

image:
  repository: aniket036/aiops-app
  tag: d4534462e774e8650d1c03a4e40c6ee384597bf5
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

hpa:
  minReplicas: 2
  maxReplicas: 5
  cpu: 70

postgres:
  user: devops
  password: devops123
  db: bookstore

config:
  db_host: ""
  db_port: "5432"
